Prevent errors while recording huge latencies
java.lang.ArrayIndexOutOfBoundsException: value 111770218 outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 1397949
	at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:571) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:563) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:467) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at org.HdrHistogram.Recorder.recordValue(Recorder.java:136) ~[org.hdrhistogram-HdrHistogram-2.1.12.jar:2.1.12]
	at io.openmessaging.benchmark.worker.LocalWorker.lambda(LocalWorker.java:233) ~[io.openmessaging.benchmark-benchmark-framework-0.0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_322]
	... 21 more